name: Detect Changes

on:
  workflow_call:
    inputs:
      change_filters:
        required: true
        type: string
    outputs:
      any_changed:
        description: "Whether any path has changed"
        value: ${{ jobs.detect.outputs.any_changed }}

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.result.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v4

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: ${{ inputs.change_filters }}

      - name: Export result
        id: result
        run: |
          echo "Changes: ${{ steps.filter.outputs.changes }}"
          if [ "${{ steps.filter.outputs.changes }}" != "[]" ]; then
            echo "any_changed=true" >> $GITHUB_OUTPUT
          else
            echo "any_changed=false" >> $GITHUB_OUTPUT
          fi